### ISSUE TITLE
In Admin "Subscribers" view, the "Created" column is empty.

### ISSUE THREAD

**Issue by canyousayyes** [zeen101/leaky-paywall#10]
### Issue

Page URL: `<domain>/wp-admin/admin.php?page=leaky-paywall-subscribers`

Inside the table, the "Created" column is always empty.

![image](https://user-images.githubusercontent.com/3950187/30319632-f991bbfa-97e2-11e7-9524-c68f32e0f835.png)

### Debug

When tracing the codes, the column is reading from user meta `_issuem_leaky_paywall_live_created / _issuem_leaky_paywall_test_created`

Related codes:
https://github.com/zeen101/leaky-paywall/blob/master/subscriber-table.php#L318

But there's no codes that updates the user meta (at least I couldn't find any).
We're using the Stripe as the payment gateway and setup other payment method.

### Suggestion

In my guess, I think the plugin have to write this user meta when created a subscription in the Stripe gateway:

https://github.com/zeen101/leaky-paywall/blob/master/include/gateways/class-leaky-paywall-payment-gateway-stripe.php#L301

**Comment by greenhornet79** [comment]
The 'created' value gets set here: https://github.com/zeen101/leaky-paywall/blob/master/include/registration-functions.php#L105

Do you have a filter running that might be altering the data?

**Comment by canyousayyes** [comment]
@greenhornet79 
We do have some alteration on user meta so the "created" meta go missing.

We'll take care of their own. Thanks for the help.
