### ISSUE TITLE
leaky_paywall_profile_your_profile_before_submit filter not functioning properly

### ISSUE THREAD

**Issue by inerds** [zeen101/leaky-paywall#105]
This filter is not injecting code before the submit button. 
Instead, it is injecting to the top of the page.

`
add_action( 'leaky_paywall_profile_your_profile_before_submit',  'htlr_before_submit'   );
function htlr_before_submit() { 
    echo '<h2>Hi there</h2>';
}
`

Filter applied just before logout link `leaky-paywall-logout-link` at the top of the page.

**Comment by greenhornet79** [comment]
It is a filter, so you need to return the output instead of using echo.

https://wpshout.com/wordpress-hooks-actions-filters/

**Comment by inerds** [comment]
Thank you @greenhornet79 . 
Appreciate it 🙏.
