### ISSUE TITLE
Creating permissions for non-admin users to access Leaky Paywall settings

### ISSUE THREAD

**Issue by danitamtd** [zeen101/leaky-paywall#106]
Hi,

We would like to create Wordpress permissions for non-admin users to access Leaky Paywall's settings, subscribers, transactions and add-on tab.

Is it possible for this functionality to be developed?

Thank you!

**Comment by greenhornet79** [comment]
Hello, you can do that with a filter.  Here is documentation on how to add the functionality to your site.

https://docs.zeen101.com/article/321-how-allow-an-editor-or-author-to-manage-leaky-paywall-settings
