### ISSUE TITLE
Filter to handle every subscription purchase?

### ISSUE THREAD

**Issue by samueldjack** [zeen101/leaky-paywall#28]
We're considering using Leaky Paywall, but have a requirement to hook it up with a back office system which handles print-edition subscriptions and also links with our accountancy software. For every subscription purchased we need to make a record in the other system so that it can create the appropriate invoices etc.

How might I accomplish this? 

Are there filters which are called on every purchase? I've seen the article about leaky_paywall_new_subscriber, but I'm guessing that doesn't get called if an existing customer renews their subscription?

**Comment by greenhornet79** [comment]
If you use Stripe as the payment gateway, there are hooks that fire every time a payment event is sent from Stripe to Leaky Paywall.

**Comment by samueldjack** [comment]
Thanks Jeremy.

Given this, it seems then that I might be able to accomplish the same thing by handling the Webhooks in our Back Office system. I'd just need to make sure that the Stripe events contain sufficient metadata to connect the dots.
