### ISSUE TITLE
No Password In Email

### ISSUE THREAD

**Issue by tikrin** [zeen101/leaky-paywall#33]
If you use the Stripe Pop Up, then the new subscriber email does not have a password sent with it.

https://github.com/zeen101/leaky-paywall/blob/d4609db796ff2d00243dd361d5dec2fa747d348c/functions.php#L2180-L2185

**Comment by tikrin** [comment]
Password arg gets unset at line 727, so then when it gets asked for again at 2182, it's blank. Users will be automatically logged in after subscription, but will have to reset their password after that to get in.

**Comment by greenhornet79** [comment]
Fixed in 4.10.10
