### ISSUE TITLE
Hidden Subscription Cards Still Registerable

### ISSUE THREAD

**Issue by tikrin** [zeen101/leaky-paywall#40]
Even if you hide a subscription card, an user can change the level_id query string to the ID of one that is hidden, and it'll still let you register for it.

**Comment by greenhornet79** [comment]
Yes, that is true. Hiding a subscription simply keeps it from displaying on the subscribe page. That way you can create private levels that you can still let someone sign up for. If you don't want someone to sign up for a level at all, then you would need to delete it.
