### ISSUE TITLE
renewal reminder cron not triggering action

### ISSUE THREAD

**Issue by greenhornet79** [zeen101/leaky-paywall#44]
ensure that whatever the fix is doesn't accidentally activate retroactively. That is, once it's fixed, make sure that when people enable those renewal e-mails again, it doesn't end up trying to go back and send the ones that weren't sent out before because I imagine I'm not the only user who has sent them out manually, so wouldn't want duplicates.

**Comment by omkalfatring** [comment]
I'm managing a site where the renewal reminder emails are not being sent.

Is this a bug across all installations of LP or does it depend on the server settings?

**Comment by greenhornet79** [comment]
This is fixed in latest release 4.12.1
