### ISSUE TITLE
Pantheon Requires Specific Cookie Naming Convention

### ISSUE THREAD

**Issue by tikrin** [zeen101/leaky-paywall#51]
https://pantheon.io/docs/cookies/

Cache-Varying Cookies
Respond to a request with cached content depending on the presence and value of a particular cookie. It's important to note that in order for the response to be cached by Pantheon's edge, the cookie name must match STYXKEY[a-zA-Z0-9_-]+

**Comment by greenhornet79** [comment]
We added a filter for that a while ago.

https://zeen101.helpscoutdocs.com/article/53-how-to-change-the-name-of-the-leaky-paywall-restriction-cookie
