### ISSUE TITLE
Category Restrictions

### ISSUE THREAD

**Issue by tikrin** [zeen101/leaky-paywall#66]
When setting subscription levels to be restricted to certain categories within post type, it does not seem to lock out of categories that they shouldn't have access to by default. Only when changing the individual visibility settings does this seem to resolve. This has been observed with regular LP. Not confirmed to be the case in alternative restriction mode.

See internal ticket number 23010 for more information.

**Comment by greenhornet79** [comment]
This was fixed in version 4.12.9
