### ISSUE TITLE
Login directed to Wordpress Login

### ISSUE THREAD

**Issue by nikhilaanumukonda** [zeen101/leaky-paywall#72]
Clicking on Login button directs the user to Wordpress Login page(wp-login) instead of the page from where the user Logins in. How can I resolve this issue ?

**Comment by greenhornet79** [comment]
What is the URL to the page where your login button lives?

**Comment by nikhilaanumukonda** [comment]
It is https://rareposts.com/l-login

Thanks
Nikhila

**Comment by greenhornet79** [comment]
All I see on that page is the shortcode "[leaky_paywall_login]". You'll need to activate Leaky Paywall for the shortcode to show a login form.

**Comment by nikhilaanumukonda** [comment]
Hi,

I am currently using Paid subscription. I have disabled Leaky wall as it
does not work. You need to login, enable it and test.

The URL for Login is https://rareposts.com/l-login. I have already given
you login details for wordpress.

Regards
Nikhila

**Comment by greenhornet79** [comment]
This github repo isn't for general support requests. Please check out our docs and support here: https://zeen101.helpscoutdocs.com/
