### ISSUE TITLE
Custom Fields Not Showing in User Account

### ISSUE THREAD

**Issue by benjaminthedev** [zeen101/leaky-paywall#78]
Hi folks, 

I used this:

https://gist.github.com/greenhornet79/8893e8ca508b8a81afcb244bf92fcec6

To create custom fields which I believe to be working when testing but these are not showing up in the users account (my account)

Heres my code:

`// leaky_paywall here
// add fields to registration form

add_action( 'leaky_paywall_after_password_registration_field', 'zeen101_custom_registration_fields' );
function zeen101_custom_registration_fields() {
  ?>
  <div class="form-row">
		<label>Company</label>
  		<input type="text" value="" name="company">
	</div>

 	<div class="form-row">
    <label>Role</label>
  		<input type="text" value="" name="role">
	</div>

  <div class="form-row">
    <label>Phone Number</label>
      <input type="text" value="" name="phonenumber">
  </div>

  <div class="form-row">
    <label>Billing Address</label>
      <input type="textbox" value="" name="address">
  </div>
  <?php

}

// save fields if user is created
add_action( 'leaky_paywall_form_processing', 'zeen101_custom_registration_fields_save', 10, 5 );
function zeen101_custom_registration_fields_save( $post_data, $user_id, $price, $mode, $site ) {

  if ( $post_data['company'] ) {
    update_user_meta( $user_id, '_company', sanitize_text_field( $post_data['company'] ) );
  }

  if ( $post_data['role'] ) {
    update_user_meta( $user_id, '_role', sanitize_text_field( $post_data['role'] ) );
  }

  if ( $post_data['phonenumber'] ) {
    update_user_meta( $user_id, '_phonenumber', sanitize_text_field( $post_data['phonenumber'] ) );
  }

  if ( $post_data['address'] ) {
    update_user_meta( $user_id, '_address', sanitize_text_field( $post_data['address'] ) );
  }

}

// display the field in the user's WP admin profile
add_action( 'show_user_profile', 'zeen101_admin_custom_fields', 99 );
add_action( 'edit_user_profile', 'zeen101_admin_custom_fields', 99 );

function zeen101_admin_custom_fields( $user ) {

	 $company = get_user_meta( $user->ID, '_company', true );
   $role = get_user_meta( $user->ID, '_role', true );
   $phonenumber = get_user_meta( $user->ID, '_phonenumber', true );
   $address = get_user_meta( $user->ID, '_address', true );

  //$newsletter = get_user_meta( $user->ID, '_newsletter_subscribe', true );
	?>
	<div class="leaky-paywall-account-fields">
  <table class="form-table">

	 <tr>
		<th><label>Company</label></th>
		<td>
			<?php echo $company; ?>
		</td>
	</tr>

	<tr>
		<th><label>Role</label></th>
		<td>
			<?php echo $role; ?>
		</td>
	</tr>

  <tr>
		<th><label>Phone Number</label></th>
		<td>
			<?php echo $phonenumber; ?>
		</td>
	</tr>

  <tr>
    <th><label>Address</label></th>
    <td>
      <?php echo $address; ?>
    </td>
  </tr>

  </table>
</div>
<?php
}

// add custom field data to Leaky Paywall Reporting Tool export
add_filter( 'leaky_paywall_reporting_tool_meta', 'zeen101_reporting_tool_custom_fields_headers' );

function zeen101_reporting_tool_custom_fields_headers( $meta ) {
	$meta[] = 'company';
  $meta[] = 'role';
  $meta[] = 'phonenumber';
  $meta[] = 'address';

  //$meta[] = 'newsletter_signup';
	return $meta;
}

add_filter( 'leaky_paywall_reporting_tool_user_meta', 'zeen101_reporting_tool_custom_fields_values', 10, 2 );

function zeen101_reporting_tool_custom_fields_values( $user_meta, $user_id ) {
	$company = get_user_meta( $user_id, '_company', true );
  $role = get_user_meta( $user_id, '_role', true );
  $phonenumber = get_user_meta( $user_id, '_phonenumber', true );
  $address = get_user_meta( $user_id, '_address', true );
	//$newsletter = get_user_meta( $user_id, '_newsletter_subscribe', true );

	$user_meta[$user_id]['company'] = $company;
  $user_meta[$user_id]['role'] = $role;
  $user_meta[$user_id]['phonenumber'] = $phonenumber;
  $user_meta[$user_id]['address'] = $address;
	//$user_meta[$user_id]['newsletter_signup'] = $newsletter;
	return $user_meta;
}

// end leaky_paywall here`

Please help!

**Comment by greenhornet79** [comment]
Are the custom fields showing up in the csv when do an export using the Leaky Paywall Reporting Tool?

**Comment by benjaminthedev** [comment]
It doesn't look like it.

**Comment by benjaminthedev** [comment]
When I run the reports I see this:

![Screenshot 2019-07-25 at 16 16 58](https://user-images.githubusercontent.com/14097672/61886473-b5b1e300-aef7-11e9-97b6-ff2db335c55f.png)

**Comment by benjaminthedev** [comment]
I assume you're talking about this reporting tool right:

![Screenshot 2019-07-25 at 16 18 04](https://user-images.githubusercontent.com/14097672/61886580-e003a080-aef7-11e9-8ee1-f12cb27b62b6.png)

**Comment by benjaminthedev** [comment]
Anyone??

**Comment by greenhornet79** [comment]
If it's not in your reporting tool export, then the fields aren't getting saved correctly. Do you have a url where your registration form lives so I can take a look?

**Comment by benjaminthedev** [comment]
Hey, yes I do. Can you send me your email and we can go from there. I also have Ty helping me on this too but all the help I can get is great!

Cheers, 

Ben.

**Comment by greenhornet79** [comment]
If you're in our support system already I check in there.

**Comment by benjaminthedev** [comment]
Thanks but no one has got back to me all week on email.
