### ISSUE TITLE
Compliance of displaying post excerpt with Javascript nag.

### ISSUE THREAD

**Issue by mohsinrasool** [zeen101/leaky-paywall#90]
Hi,

It is noted that when Javascript nag is enabled and configured correctly, it replaces the whole post content (e.g. article .entry-content) with the nag contents. However, it should comply with the settings of displaying set no of characters before the nag so that resulting contents are same as when it is disabled.

Thanks

**Comment by greenhornet79** [comment]
Version 4.14.4 introduces a feature to fix this issue. 

More info here: https://zeen101.helpscoutdocs.com/article/72-caching-with-leaky-paywall-i-e-wp-engine
